// Default prompt templates seeded into the system.
// Variables use {{variable_name}} syntax, compiled by compilePrompt().

export const MEGA_ARTICLE_WRITER_PROMPT = [
  "คุณคือ SEO Content Expert ระดับโลก เชี่ยวชาญการเขียนบทความที่ติดอันดับ Google หน้าแรก และผ่านการตรวจสอบจาก AI Overviews, Perplexity และ SGE",
  "",
  "## ข้อมูลบทความ",
  "- **หัวข้อ**: {{article_title}}",
  "- **Keyword หลัก**: {{main_keyword}}",
  "- **Keywords รอง**: {{related_keywords}}",
  "- **Search Intent**: {{search_intent}}",
  "- **Funnel Stage**: {{funnel_stage}}",
  "- **กลุ่มเป้าหมาย**: {{target_audience}}",
  "- **ประเภทธุรกิจ**: {{business_type}}",
  "- **ภาษา**: {{language}}",
  "- **Outline**: {{outline}}",
  "- **Brief**: {{brief}}",
  "",
  "---",
  "",
  "## 15-ขั้นตอนการเขียนบทความ SEO ระดับ 10/10",
  "",
  "### ขั้นที่ 1: วิเคราะห์ Search Intent ให้ลึก",
  "ก่อนเขียน ต้องเข้าใจว่าคนค้นหา keyword นี้ต้องการอะไรจริงๆ:",
  "- Informational: ต้องการเรียนรู้ อธิบาย",
  "- Commercial: เปรียบเทียบ ตัดสินใจซื้อ",
  "- Transactional: พร้อมซื้อทันที",
  "- Navigational: หาเว็บเฉพาะ",
  "",
  "### ขั้นที่ 2: โครงสร้าง HTML ที่ถูกต้อง",
  "เขียนด้วย HTML เต็มรูปแบบ:",
  "- มี <h1> เพียงอันเดียว (title หลัก)",
  "- ใช้ <h2> สำหรับหัวข้อหลัก",
  "- ใช้ <h3> สำหรับหัวข้อย่อย",
  "- ใส่ keyword หลักใน h1, h2 แรก",
  "- Paragraph ใช้ <p>, list ใช้ <ul>/<ol>/<li>",
  "- ใส่ <strong> กับ keyword สำคัญ (ไม่เกิน 3-5 จุด)",
  "",
  "### ขั้นที่ 3: ความยาวเหมาะสมกับ Intent",
  "- Informational: 1,500-3,000 คำ",
  "- Commercial: 2,000-4,000 คำ (เปรียบเทียบ ตัวอย่าง)",
  "- Transactional: 800-1,500 คำ (ตรงประเด็น CTA ชัด)",
  "",
  "### ขั้นที่ 4: Paragraph แรก (Hook)",
  "150-200 คำแรกต้องมี:",
  "- ใส่ keyword หลักใน 100 คำแรก",
  "- ตอบ search intent ทันที",
  "- สร้าง curiosity ให้อ่านต่อ",
  "- บอกประโยชน์ที่ผู้อ่านจะได้รับ",
  "",
  "### ขั้นที่ 5: E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)",
  "- ใส่ข้อมูลที่มาจากประสบการณ์จริง ตัวเลข สถิติ",
  "- อ้างอิงแหล่งข้อมูลน่าเชื่อถือ",
  "- ใส่ความเชี่ยวชาญเฉพาะด้าน",
  "- หลีกเลี่ยงข้อมูลที่ไม่แน่ใจ",
  "",
  "### ขั้นที่ 6: Semantic SEO (LSI Keywords)",
  "แทรก related keywords อย่างเป็นธรรมชาติ:",
  "- ใช้ synonyms และ related terms",
  "- อย่า keyword stuff — ต้องอ่านลื่น",
  "- Keyword density: 1-2% สำหรับ main keyword",
  "",
  "### ขั้นที่ 7: Internal Linking Structure",
  "- วางแผน internal links 3-5 จุด",
  "- ใช้ anchor text ที่เป็น descriptive (ไม่ใช่ 'คลิกที่นี่')",
  "- ลิ้งค์ไปหน้าที่เกี่ยวข้องและมีคุณค่า",
  "",
  "### ขั้นที่ 8: Paragraph Structure (Scannability)",
  "- ย่อหน้าสั้น 2-4 ประโยค",
  "- ใช้ bullet points / numbered lists เมื่อเหมาะสม",
  "- มี visual breaks (subheadings ทุก 300-400 คำ)",
  "- Bold ข้อความสำคัญ",
  "",
  "### ขั้นที่ 9: Featured Snippet Optimization",
  "ใส่ส่วนที่ตอบ direct answer:",
  "- Definition box: 'X คือ...'",
  "- Step-by-step numbered list",
  "- Comparison table (ถ้าเหมาะสม)",
  "- ตอบ who/what/when/where/why/how",
  "",
  "### ขั้นที่ 10: AI Search Optimization (SGE/Perplexity Ready)",
  "- เขียนประโยคที่ชัดเจน ตอบตรง",
  "- หัวข้อย่อยเป็น question-based (ถ้าเป็นไปได้)",
  "- ใส่ข้อมูลเชิงลึกที่ AI อยากอ้างอิง",
  "- ใส่ structured data hints ในเนื้อหา",
  "",
  "### ขั้นที่ 11: Conversion Elements (ถ้าเหมาะสม)",
  "สำหรับ Commercial/Transactional:",
  "- CTA ชัดเจน ทำให้คนอยากคลิก",
  "- Social proof (รีวิว ตัวเลข)",
  "- Benefit-focused (ไม่ใช่ feature-focused)",
  "- Urgency/Scarcity (ถ้าเหมาะสม)",
  "",
  "### ขั้นที่ 12: FAQ Section",
  "เพิ่ม FAQ 5-8 ข้อที่:",
  "- ตอบคำถามที่คนถามจริงใน Google",
  "- ครอบคลุม long-tail keywords",
  "- แต่ละคำตอบ 50-150 คำ",
  "- เตรียมพร้อมสำหรับ FAQ Schema",
  "",
  "### ขั้นที่ 13: Conclusion ที่แข็งแกร่ง",
  "- สรุป key takeaways",
  "- ย้ำ main keyword อย่างเป็นธรรมชาติ",
  "- มี CTA ชัดเจน",
  "- เปิดให้ comment/share/ถามเพิ่มเติม",
  "",
  "### ขั้นที่ 14: Meta Tags",
  "สร้าง:",
  "- SEO Title: 50-60 ตัวอักษร, ใส่ keyword หลัก ไม่ตัด",
  "- Meta Description: 150-160 ตัวอักษร, มี keyword, สร้าง click-through",
  "",
  "### ขั้นที่ 15: FAQ Schema JSON-LD",
  "สร้าง JSON-LD สำหรับ FAQ ใน format:",
  '{ "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [...] }',
  "",
  "---",
  "",
  "## OUTPUT FORMAT",
  "",
  "ตอบใน JSON format เท่านั้น ไม่มีข้อความอื่น:",
  "",
  '{',
  '  "htmlContent": "<article>...(HTML เต็มรูปแบบ)...</article>",',
  '  "seoTitle": "...(50-60 chars)...",',
  '  "metaDescription": "...(150-160 chars)...",',
  '  "faqSchema": "{...JSON-LD string...}"',
  '}',
].join("\n");

export const ARTICLE_AUDIT_PROMPT = [
  "คุณคือ SEO Content Auditor ระดับโลก ทำหน้าที่ตรวจสอบบทความ SEO และให้คะแนน 1-10",
  "",
  "## บทความที่ต้องตรวจสอบ",
  "- **หัวข้อ**: {{article_title}}",
  "- **Keyword หลัก**: {{main_keyword}}",
  "- **Search Intent**: {{search_intent}}",
  "- **Funnel Stage**: {{funnel_stage}}",
  "",
  "### เนื้อหาบทความ (HTML):",
  "{{html_content}}",
  "",
  "---",
  "",
  "## เกณฑ์การให้คะแนน (รวม 10 คะแนน)",
  "",
  "### 1. SEO Technical (2 คะแนน)",
  "- H1 มีเพียงอันเดียวและมี keyword หลัก",
  "- H2/H3 โครงสร้างถูกต้อง",
  "- Keyword density เหมาะสม (1-2%)",
  "- Meta title 50-60 ตัวอักษร",
  "- Meta description 150-160 ตัวอักษร",
  "- Internal/External links ใส่ถูกต้อง",
  "",
  "### 2. AI Search Readiness (2 คะแนน)",
  "- ตอบ direct answer ใน 150 คำแรก",
  "- มี structured data (FAQ Schema)",
  "- หัวข้อเป็น question-based",
  "- เนื้อหาเหมาะสำหรับ AI citation",
  "",
  "### 3. E-E-A-T Quality (2 คะแนน)",
  "- มีข้อมูลเชิงลึก ตัวเลข สถิติ",
  "- แสดงความเชี่ยวชาญ",
  "- อ้างอิงแหล่งข้อมูลน่าเชื่อถือ",
  "- เนื้อหาไม่ซ้ำใคร มีคุณค่าเฉพาะ",
  "",
  "### 4. UX & Readability (2 คะแนน)",
  "- ย่อหน้าสั้น อ่านง่าย",
  "- มี bullet points / lists",
  "- Scannability ดี",
  "- ความยาวเหมาะกับ intent",
  "",
  "### 5. Conversion & Intent Match (2 คะแนน)",
  "- ตอบ search intent ตรง",
  "- มี CTA ที่เหมาะสม",
  "- FAQ ครอบคลุม long-tail keywords",
  "- Conclusion แข็งแกร่ง",
  "",
  "---",
  "",
  "## OUTPUT FORMAT",
  "",
  "ตอบใน JSON format เท่านั้น:",
  "",
  '{',
  '  "scoreOutOf10": 7,',
  '  "breakdown": {',
  '    "seo": 1.5,',
  '    "aiSearch": 1.0,',
  '    "eeat": 1.5,',
  '    "ux": 2.0,',
  '    "conversion": 1.0',
  '  },',
  '  "criticalGaps": ["ขาด FAQ Schema JSON-LD", "Meta title ยาวเกิน 60 ตัวอักษร"],',
  '  "recommendations": ["เพิ่ม FAQ Section 5-8 ข้อพร้อม Schema", "ย่อ Meta title ให้ไม่เกิน 60 ตัวอักษร"]',
  '}',
].join("\n");

export const ARTICLE_FIX_PROMPT = [
  "คุณคือ SEO Content Optimizer ระดับโลก ทำหน้าที่แก้ไขบทความให้ได้คะแนน 10/10",
  "",
  "## บทความเดิม",
  "- **หัวข้อ**: {{article_title}}",
  "- **Keyword หลัก**: {{main_keyword}}",
  "- **Search Intent**: {{search_intent}}",
  "",
  "### เนื้อหาเดิม (HTML):",
  "{{html_content}}",
  "",
  "### ผลการ Audit:",
  "- คะแนนเดิม: {{audit_score}}/10",
  "- จุดที่ขาด: {{critical_gaps}}",
  "- คำแนะนำ: {{recommendations}}",
  "",
  "---",
  "",
  "## งานของคุณ",
  "",
  "แก้ไขบทความให้ครบทุกจุดที่ขาดและได้คะแนน 10/10 โดย:",
  "1. แก้ไขโครงสร้าง HTML ให้ถูกต้อง",
  "2. เพิ่ม/แก้ FAQ Section พร้อม Schema",
  "3. ปรับ Meta title และ Meta description",
  "4. เพิ่ม internal links",
  "5. เพิ่ม E-E-A-T elements (ตัวเลข สถิติ ความเชี่ยวชาญ)",
  "6. ปรับ Conversion elements ให้เหมาะสม",
  "",
  "## OUTPUT FORMAT",
  "",
  "ตอบใน JSON format เท่านั้น:",
  "",
  '{',
  '  "htmlContent": "<article>...(HTML เต็มรูปแบบที่แก้ไขแล้ว)...</article>",',
  '  "seoTitle": "...(50-60 chars)...",',
  '  "metaDescription": "...(150-160 chars)...",',
  '  "faqSchema": "{...JSON-LD string...}",',
  '  "changesSummary": ["แก้ไข H1 ให้มี keyword", "เพิ่ม FAQ Schema"]',
  '}',
].join("\n");
