// Shared prompt/skill definitions — used by both API route and settings page
// Kept outside route.ts to avoid Next.js "invalid Route export" errors

export const SYSTEM_SKILLS = [
  {
    key: 'anti_spam',
    file: 'prompts/convert_cake_anti_spam.md',
    name: 'Anti-Spam Rules',
    description: 'กฎป้องกัน spam content — ห้ามซ้ำ, ห้ามเคลม, ห้ามคำต้องห้าม',
    usedIn: ['Content Studio — เขียนบทความ', 'Sales Page', 'Landing Page'],
    affectsNote: 'ส่งผลต่อทุก content ที่เขียนผ่านระบบ',
    page: 'article',
  },
  {
    key: 'internal_link_rules',
    file: 'prompts/convert_cake_internal_link_rules.md',
    name: 'Internal Link Rules',
    description: 'กฎการใส่ internal link ภายในบทความ — anchor text, context, ความถี่',
    usedIn: ['Content Studio — เขียนบทความ'],
    affectsNote: 'ส่งผลต่อการใส่ link ในทุกบทความที่เขียนใหม่',
    page: 'article',
  },
  {
    key: 'seo_meta_cover_rules',
    file: 'prompts/seo_meta_cover_rules.md',
    name: 'SEO Meta & Cover Rules',
    description: 'กฎการสร้าง meta title, meta description, cover image prompt ที่ถูกต้อง',
    usedIn: ['Content Studio — เขียนบทความ', 'Image Studio — สร้างรูปปก'],
    affectsNote: 'ส่งผลต่อ meta และ cover prompt ของทุกบทความ',
    page: 'article',
  },
  {
    key: 'comparison_prompt',
    file: 'prompts/comparison_prompt.md',
    name: 'Comparison Prompt',
    description: 'Skill เขียนบทความเปรียบเทียบ — table, pros/cons, verdict',
    usedIn: ['Content Studio — เขียนบทความ (Comparison type)'],
    affectsNote: 'ส่งผลเฉพาะบทความประเภท Comparison',
    page: 'article',
  },
  {
    key: 'cover_validator',
    file: 'prompts/cover_validator_prompt.md',
    name: 'Cover Image Validator',
    description: 'Checklist ตรวจสอบคุณภาพ cover image prompt ก่อน generate',
    usedIn: ['Image Studio — generate รูปปก'],
    affectsNote: 'ส่งผลต่อคุณภาพ prompt ที่ส่งไป Gemini Imagen',
    page: 'image',
  },
]

export const CODE_SKILLS = [
  {
    key: 'keyword_research',
    name: 'Keyword Research Skill',
    description: 'ค้นหา keyword ด้วย Google Grounding — volume, intent, cluster, journey stage',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/keywordResearchSkill.ts',
  },
  {
    key: 'seo_title_ai',
    name: 'SEO Title AI Skill',
    description: 'Generate SEO title ที่ optimize สำหรับ Thai search — keyword placement, length, click-through',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/seoTitleAiSkill.ts',
  },
  {
    key: 'aeo_skill',
    name: 'AEO / AI Search Skill',
    description: 'วิเคราะห์ AEO risk, AI Overview, GEO opportunity ของแต่ละ keyword',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/aeoSkill.ts',
  },
  {
    key: 'competitor_gap',
    name: 'Competitor Gap Skill',
    description: 'Score ว่า keyword ไหนที่ competitor ใหญ่พลาด — หา gap เพื่อ rank ได้เร็ว',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/competitorGapSkill.ts',
  },
  {
    key: 'topic_cluster',
    name: 'Topic Cluster Skill',
    description: 'จัดกลุ่ม keyword เป็น cluster — parent topic, cluster topic, FAQ, supporting',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/topicClusterSkill.ts',
  },
  {
    key: 'trend_skill',
    name: 'Trend Detection Skill',
    description: 'จัดประเภท keyword ตาม seasonality — evergreen, seasonal, trending, declining',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/trendSkill.ts',
  },
  {
    key: 'problem_first',
    name: 'Problem-First Skill',
    description: 'ค้นหา keyword จากมุม pain point ของลูกค้า — gap-fill strategy',
    usedIn: ['Keyword Research (Wordgod)'],
    page: 'keyword',
    file: 'src/lib/skills/problemFirstSkill.ts',
  },
  {
    key: 'article_review',
    name: 'Article Review Skill',
    description: 'วิเคราะห์คุณภาพบทความ — SEO score, readability, conversion, issues',
    usedIn: ['Content Studio', 'Review'],
    page: 'article',
    file: 'src/app/api/article/review/route.ts',
  },
]

export const SYSTEM_PROMPTS = [
  {
    key: 'global_rules',
    file: 'prompts/global_rules.md',
    name: 'Global Rules',
    category: 'article',
    description: 'กฎพื้นฐานที่ใช้กับทุก content generation — ความถูกต้อง, UX, SEO, conversion',
    usedIn: ['Content Studio — เขียนบทความ'],
    affectsNote: 'ส่งผลต่อทุกบทความที่เขียนผ่านระบบ (system-wide)',
  },
  {
    key: 'master_prompt',
    file: 'prompts/convert_cake_seo_master.md',
    name: 'Master Prompt (SEO Article)',
    category: 'article',
    description: 'Prompt หลักสำหรับเขียนบทความ SEO — โครงสร้าง, HTML, schema, CTA',
    usedIn: ['Content Studio — เขียนบทความ'],
    affectsNote: 'ส่งผลต่อโครงสร้างและรูปแบบบทความทุกชิ้น',
  },
  {
    key: 'validator',
    file: 'prompts/convert_cake_validator_10_10.md',
    name: 'Validator 10/10',
    category: 'article',
    description: 'Checklist ตรวจสอบคุณภาพบทความก่อน output — SEO, readability, conversion',
    usedIn: ['Content Studio — เขียนบทความ'],
    affectsNote: 'ส่งผลต่อ quality check ก่อน output บทความทุกชิ้น',
  },
  {
    key: 'article_review',
    file: 'prompts/article_review_prompt.md',
    name: 'Article Review Prompt',
    category: 'article',
    description: 'วิเคราะห์บทความและให้คำแนะนำ SEO, E-E-A-T, Readability, Conversion',
    usedIn: ['Content Studio — แท็บ Review & Suggestions'],
    affectsNote: 'ส่งผลต่อ AI suggestions ที่ขึ้นหลังเขียนบทความเสร็จ',
  },
  {
    key: 'cover_master',
    file: 'prompts/cover_master_prompt.md',
    name: 'Cover Image Master',
    category: 'image',
    description: 'Prompt สำหรับ generate รูปปก article ด้วย Gemini Imagen',
    usedIn: ['Image Studio — generate รูปปก'],
    affectsNote: 'ส่งผลต่อ prompt ที่ส่งไป AI image generator ทุกครั้ง',
  },
  {
    key: 'seo_article',
    file: 'prompts/seo_article_prompt.md',
    name: 'SEO Article (Alt)',
    category: 'article',
    description: 'Prompt บทความ SEO แบบ alternate — ใช้สำหรับ content type พิเศษ',
    usedIn: ['Content Studio — content type พิเศษ'],
    affectsNote: 'ส่งผลเฉพาะบทความ type พิเศษที่เลือกใช้ prompt นี้',
  },
  {
    key: 'landing_page',
    file: 'prompts/landing_page_prompt.md',
    name: 'Landing Page',
    category: 'page',
    description: 'Prompt สำหรับสร้าง landing page เน้น conversion',
    usedIn: ['Content Studio — Landing Page type'],
    affectsNote: 'ส่งผลเฉพาะ content ประเภท Landing Page',
  },
  {
    key: 'sales_page',
    file: 'prompts/sales_page_prompt.md',
    name: 'Sales Page',
    category: 'page',
    description: 'Prompt สำหรับสร้าง sales page เน้น persuasion',
    usedIn: ['Content Studio — Sales Page type'],
    affectsNote: 'ส่งผลเฉพาะ content ประเภท Sales Page',
  },
  {
    key: 'email_copy',
    file: 'prompts/email_copy_prompt.md',
    name: 'Email Copy',
    category: 'email',
    description: 'Prompt สำหรับเขียน email marketing copy',
    usedIn: ['Content Studio — Email Copy type'],
    affectsNote: 'ส่งผลเฉพาะ content ประเภท Email Copy',
  },
  {
    key: 'social_caption',
    file: 'prompts/social_caption_prompt.md',
    name: 'Social Caption',
    category: 'social',
    description: 'Prompt สำหรับเขียน caption โซเชียล',
    usedIn: ['Content Studio — Social Caption type'],
    affectsNote: 'ส่งผลเฉพาะ content ประเภท Social Caption',
  },
  {
    key: 'product_review',
    file: 'prompts/product_review_prompt.md',
    name: 'Product Review',
    category: 'article',
    description: 'Prompt สำหรับเขียนรีวิวสินค้า',
    usedIn: ['Content Studio — Product Review type'],
    affectsNote: 'ส่งผลเฉพาะบทความประเภท Product Review',
  },
]

export const STUDIO_PROMPT_KEYS = ['global_rules', 'master_prompt', 'validator', 'article_review', 'cover_master']
