/**
 * Client Report API
 * POST /api/report — generate HTML report for a project
 * Returns: HTML string ready to print-to-PDF or email
 */
import { NextRequest, NextResponse } from "next/server";

import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session?.user?.organizationId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const orgId = session.user.organizationId;
  const { projectId, month } = await req.json() as { projectId: string; month?: string };

  const project = await prisma.project.findFirst({
    where: { id: projectId, organizationId: orgId },
    include: { owner: { select: { name: true } } },
  });
  if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });

  const now = new Date();
  const reportDate = month ? new Date(month) : now;
  const startOfMonth = new Date(reportDate.getFullYear(), reportDate.getMonth(), 1);
  const endOfMonth   = new Date(reportDate.getFullYear(), reportDate.getMonth() + 1, 0);
  const monthLabel   = reportDate.toLocaleDateString("th-TH", { year: "numeric", month: "long" });

  const [articles, aiJobs] = await Promise.all([
    prisma.article.findMany({
      where: { projectId, updatedAt: { gte: startOfMonth, lte: endOfMonth } },
      select: {
        id: true, title: true, status: true, funnelStage: true,
        wordpressUrl: true, auditScore: true, refreshScore: true,
        keyword: { select: { keyword: true } },
        rankSnapshots: { orderBy: { snapshotAt: "desc" }, take: 1 },
      },
      orderBy: { updatedAt: "desc" },
    }),
    prisma.aIJob.aggregate({
      where: { projectId, createdAt: { gte: startOfMonth, lte: endOfMonth } },
      _sum: { estimatedCost: true },
      _count: { id: true },
    }),
  ]);

  const posted   = articles.filter((a) => a.status === "POSTED").length;
  const approved = articles.filter((a) => a.status === "APPROVED").length;
  const drafted  = articles.filter((a) => a.status === "WORDPRESS_DRAFTED").length;
  const aiCost   = aiJobs._sum.estimatedCost ?? 0;
  const avgAudit = articles.filter((a) => a.auditScore).reduce((s, a) => s + (a.auditScore ?? 0), 0) / (articles.filter((a) => a.auditScore).length || 1);

  const html = `<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>SEO Report — ${project.name} — ${monthLabel}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Sarabun', sans-serif; background: #f8f9fa; color: #1a1a1a; font-size: 14px; }
  .page { max-width: 900px; margin: 0 auto; padding: 40px 24px; }
  .header { background: linear-gradient(135deg, #1A2D60, #1E3A7A); color: white; border-radius: 16px; padding: 32px; margin-bottom: 28px; }
  .header h1 { font-size: 28px; font-weight: 700; margin-bottom: 4px; }
  .header p  { opacity: 0.7; font-size: 13px; }
  .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 28px; }
  .kpi { background: white; border-radius: 12px; padding: 20px; border: 1px solid #e5e7eb; text-align: center; }
  .kpi .value { font-size: 32px; font-weight: 700; color: #1a1a1a; }
  .kpi .label { font-size: 12px; color: #6b7280; margin-top: 4px; }
  .kpi.green .value { color: #059669; }
  .kpi.blue  .value { color: #2563eb; }
  .kpi.amber .value { color: #d97706; }
  .section { background: white; border-radius: 12px; padding: 24px; border: 1px solid #e5e7eb; margin-bottom: 20px; }
  .section h2 { font-size: 16px; font-weight: 700; margin-bottom: 16px; color: #111827; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; padding: 8px 12px; font-size: 11px; font-weight: 600; color: #6b7280; text-transform: uppercase; border-bottom: 2px solid #f3f4f6; }
  td { padding: 10px 12px; font-size: 13px; border-bottom: 1px solid #f9fafb; color: #374151; }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-flex; align-items: center; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
  .badge.green  { background: #d1fae5; color: #065f46; }
  .badge.blue   { background: #dbeafe; color: #1e40af; }
  .badge.amber  { background: #fef3c7; color: #92400e; }
  .badge.gray   { background: #f3f4f6; color: #4b5563; }
  .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
  @media print { body { background: white; } .page { padding: 20px; } }
</style>
</head>
<body>
<div class="page">

  <div class="header">
    <h1>${project.name}</h1>
    <p>SEO Monthly Report · ${monthLabel} · Generated by Mars</p>
    ${project.website ? `<p style="margin-top:8px;opacity:.6;">${project.website}</p>` : ""}
  </div>

  <div class="kpi-grid">
    <div class="kpi green"><div class="value">${posted}</div><div class="label">บทความ Published</div></div>
    <div class="kpi blue"><div class="value">${articles.length}</div><div class="label">บทความทั้งหมด</div></div>
    <div class="kpi amber"><div class="value">${Math.round(avgAudit) || "—"}</div><div class="label">Avg Audit Score</div></div>
    <div class="kpi"><div class="value">$${aiCost.toFixed(2)}</div><div class="label">AI Cost</div></div>
  </div>

  <div class="section">
    <h2>สรุปบทความเดือนนี้</h2>
    <table>
      <thead><tr>
        <th>ชื่อบทความ</th>
        <th>Keyword</th>
        <th>Funnel</th>
        <th>สถานะ</th>
        <th>Audit</th>
        <th>Position</th>
      </tr></thead>
      <tbody>
        ${articles.map((a) => {
          const statusMap: Record<string, [string, string]> = {
            POSTED: ["green", "Published"], APPROVED: ["blue", "Approved"],
            WORDPRESS_DRAFTED: ["amber", "WP Draft"], SEO_REVIEW: ["amber", "In Review"],
          };
          const [cls, label] = statusMap[a.status] ?? ["gray", a.status];
          const pos = a.rankSnapshots[0]?.position;
          return `<tr>
            <td><strong>${a.title}</strong>${a.wordpressUrl ? ` <a href="${a.wordpressUrl}" style="color:#2563eb;font-size:11px;">↗</a>` : ""}</td>
            <td>${a.keyword?.keyword ?? "—"}</td>
            <td><span class="badge gray">${a.funnelStage}</span></td>
            <td><span class="badge ${cls}">${label}</span></td>
            <td>${a.auditScore ? `${a.auditScore}/100` : "—"}</td>
            <td>${pos !== undefined ? `#${Math.round(pos)}` : "—"}</td>
          </tr>`;
        }).join("")}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>สรุปภาพรวม</h2>
    <table>
      <tbody>
        <tr><td>Published</td><td><strong>${posted}</strong> บทความ</td></tr>
        <tr><td>Approved (รอ publish)</td><td><strong>${approved}</strong> บทความ</td></tr>
        <tr><td>WordPress Draft</td><td><strong>${drafted}</strong> บทความ</td></tr>
        <tr><td>AI Jobs รันเดือนนี้</td><td><strong>${aiJobs._count.id}</strong> jobs</td></tr>
        <tr><td>AI Cost เดือนนี้</td><td><strong>$${aiCost.toFixed(4)}</strong></td></tr>
      </tbody>
    </table>
  </div>

  <div class="footer">
    รายงานนี้สร้างโดย Mars SEO Platform · ${new Date().toLocaleDateString("th-TH", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="seo-report-${project.name}-${monthLabel}.html"`,
    },
  });
}
